# Generated by Django 6.0.5 on 2026-06-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activitylog_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='session',
            field=models.CharField(choices=[('Autumn', 'Autumn'), ('Spring', 'Spring')], default='Autumn', max_length=10),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='year',
            field=models.CharField(choices=[('26', '2026'), ('25', '2025'), ('24', '2024'), ('23', '2023'), ('22', '2022')], default='25', max_length=4),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='term',
            field=models.CharField(choices=[('Mid', 'Mid'), ('Final', 'Final')], default='Mid', max_length=10),
        ),
    ]
